import { Plus, Trash2 } from 'lucide-react';
import type { InventorySpool } from '../../../api/client';
import type { CalculationLine } from '../../../api/calculations';
import { NumberField , LegacySelect, TextField} from '../../ui';

export function MaterialsEditor({ lines, spools, locale, onChange }: { lines: CalculationLine[]; spools: InventorySpool[]; locale: string; onChange: (lines: CalculationLine[]) => void }) {
  const de = locale.startsWith('de');
  const materials = lines.filter(line => line.kind === 'material');
  const update = (sortOrder: number, values: Partial<CalculationLine>) => onChange(lines.map(line => line.sort_order === sortOrder ? { ...line, ...values } : line));
  return <section><div className="mb-3 flex items-center justify-between"><div><h3 className="font-semibold text-white">{de ? 'Kleinteile & Zusatzmaterial' : 'Small parts & additional material'}</h3><p className="text-xs text-bambu-gray">{de ? 'Aus dem Lager wählen oder manuell kalkulieren.' : 'Select inventory or enter a manual cost.'}</p></div><button type="button" onClick={() => onChange([...lines, { kind: 'material', description: de ? 'Zusatzmaterial' : 'Additional material', quantity: '1', unit_code: 'C62', unit_price: '0', sort_order: lines.length }])} className="inline-flex items-center gap-2 rounded bg-bambu-dark px-3 py-2 text-sm text-white"><Plus className="h-4 w-4" />{de ? 'Material' : 'Material'}</button></div>
    {materials.length === 0 ? <p className="rounded-lg bg-bambu-dark p-3 text-sm text-bambu-gray">{de ? 'Noch keine Kleinteile oder Zusatzmaterialien.' : 'No small parts or additional materials.'}</p> : <div className="space-y-2">{materials.map(line => <div key={line.sort_order} className="grid gap-2 rounded-lg bg-bambu-dark p-3 md:grid-cols-[220px_1fr_100px_130px_40px]"><LegacySelect aria-label={de ? 'Lagermaterial' : 'Inventory material'} value="" onChange={e => { const spool = spools.find(item => item.id === Number(e.target.value)); if (spool) update(line.sort_order, { description: [spool.brand, spool.material, spool.color_name].filter(Boolean).join(' · '), unit_price: String((spool.cost_per_kg ?? 0) / 1000), unit_code: 'GRM' }); }} className="h-10 rounded border border-bambu-dark-tertiary bg-bambu-dark-secondary px-3 text-white"><option value="">{de ? 'Manuell / Lager wählen' : 'Manual / select inventory'}</option>{spools.filter(item => !item.archived_at).map(item => <option key={item.id} value={item.id}>{[item.brand, item.material, item.color_name].filter(Boolean).join(' · ')}</option>)}</LegacySelect><TextField aria-label={de ? 'Materialbezeichnung' : 'Material description'} value={line.description} onChange={e => update(line.sort_order, { description: e.target.value })} className="h-10 rounded border border-bambu-dark-tertiary bg-bambu-dark-secondary px-3 text-white" /><NumberField aria-label={de ? 'Menge' : 'Quantity'}  min="0.001" step="0.01" value={line.quantity} onChange={e => update(line.sort_order, { quantity: e.target.value })} className="h-10 rounded border border-bambu-dark-tertiary bg-bambu-dark-secondary px-3 text-white" /><NumberField aria-label={de ? 'Einstandspreis' : 'Unit cost'}  min="0" step="0.01" value={line.unit_price ?? '0'} onChange={e => update(line.sort_order, { unit_price: e.target.value })} className="h-10 rounded border border-bambu-dark-tertiary bg-bambu-dark-secondary px-3 text-white" /><button type="button" aria-label={de ? 'Material löschen' : 'Remove material'} onClick={() => onChange(lines.filter(item => item.sort_order !== line.sort_order).map((item, index) => ({ ...item, sort_order: index })))} className="text-red-300"><Trash2 className="h-4 w-4" /></button></div>)}</div>}
  </section>;
}
