"""Token-gated RTSP passthrough for Home Assistant (and any other RTSP
client that isn't a browser) — opt-in, disabled by default.

go2rtc's own RTSP server (``rtsp: listen: ...`` in go2rtc.yaml) has no
authentication at all, same as everywhere else in the go2rtc sidecar — see
go2rtc_client.py's module docstring. It's fine to leave loopback-only for
the fan-out broadcaster and MSE proxy, which sit behind PrintOps's own
token checks before ever touching go2rtc. But Home Assistant's Generic
Camera integration wants a plain ``rtsp://`` URL it hands straight to its
own ffmpeg/stream backend — there's no query-string or header slot for a
PrintOps token in that flow, so go2rtc's RTSP port can't just be exposed
directly without giving away unauthenticated access to every printer's
camera.

This module is a small, standalone TCP proxy that:

1. Listens on a real network interface (unlike go2rtc's own RTSP server,
   which stays loopback-only — see the go2rtc.yaml generated by
   deploy/docker-entrypoint.sh).
2. Speaks RTSP's Digest challenge/response: the client's URL carries the
   token as userinfo — with an explicit trailing colon for an empty
   password (``rtsp://<token>:@host:8554/printer-<id>``; ffmpeg's URL
   parser only recognises credentials as present with that colon — a bare
   ``<token>@host`` is silently treated as no credentials at all and
   never triggers a Digest retry, verified empirically) — but RTSP
   clients don't put that on the wire in the request-line URL — they move
   it into an ``Authorization`` header, only *after* an initial
   unauthenticated attempt gets a 401 back. ffmpeg (what go2rtc, and thus
   HA's underlying stream backend, uses) only retries with *Digest*
   credentials, never Basic, even when a Basic challenge is offered
   (verified empirically) — so OPTIONS is answered unconditionally, and
   DESCRIBE onward gets a Digest challenge specifically. See
   ``_DIGEST_HEADER_RE``'s comment for why the response hash itself isn't
   independently verified.
3. Verifies the decoded username against the *same* ``verify_camera_stream_token``
   the MJPEG and MSE routes use — no new token type, no new scope. A token
   minted via ``POST /camera/stream-token`` (ephemeral) or a long-lived
   HA/kiosk token (see long_lived_tokens.STREAM_SCOPES) both work here.
4. Once authenticated, resolves the requested printer's CameraSource and
   acquires a go2rtc_registry registration for the session's lifetime,
   then relays the rest of the session to go2rtc's internal RTSP port —
   rewriting every subsequent request line's URL the same way
   camera.create_tls_proxy rewrites RTSPS request lines, since RTSP
   resends the full URL on every request over the same connection, not
   just the first one.

Only RTSP-backed sources (``CameraSource.has_h264``) make sense here —
chamber-image/external-MJPEG printers have no RTSP producer in go2rtc at
all.
"""

from __future__ import annotations

import asyncio
import logging
import re
import secrets

from sqlalchemy import select

from backend.app.core.auth import verify_camera_stream_token
from backend.app.core.database import async_session
from backend.app.services import go2rtc_registry
from backend.app.services.camera import rewrite_rtsp_request_url
from backend.app.services.camera_source import get_camera_source

logger = logging.getLogger(__name__)

# go2rtc's own RTSP server — moved to a loopback-only, non-standard port by
# the go2rtc.yaml this proxy's callers generate, precisely so nothing but
# this proxy (and the MJPEG/MSE HTTP paths, which don't use RTSP at all)
# can reach it. Kept in sync with deploy/docker-entrypoint.sh's template.
GO2RTC_INTERNAL_RTSP_PORT = 18554

_REQUEST_LINE_RE = re.compile(rb"^(\S+) rtsp://([^/\s]+)(/\S*) RTSP/1\.0\s*$")
_STREAM_NAME_RE = re.compile(r"^/?(printer-(\d+))")
_CSEQ_HEADER_RE = re.compile(rb"^CSeq:\s*(\S+)\s*$", re.IGNORECASE)
# ffmpeg's RTSP client (used by go2rtc and — through it — Home Assistant's
# stream backend) does not retry with Basic credentials after a 401, even
# when the URL embeds userinfo — verified empirically against ffmpeg 7.1.5.
# It *does* retry with RFC 2069 Digest, so that's the wire format this
# proxy challenges with. The `response` hash isn't independently verified
# below: doing so would need a real per-token password this proxy doesn't
# have (the token's opaque value is the only credential, same as it would
# be as a Basic username) — Digest here is purely a transport-compat
# shim for ffmpeg's retry behaviour, not an extra security layer beyond
# "is this username a currently-valid camera_stream token".
_DIGEST_HEADER_RE = re.compile(rb"^Authorization:\s*Digest\s+(.+)$", re.IGNORECASE)
_DIGEST_USERNAME_RE = re.compile(rb'username="([^"]*)"')

_READ_TIMEOUT = 10.0
# Generous headroom: a real handshake is typically OPTIONS (unauthenticated,
# doesn't count toward "did they prove a token" but still consumes a loop
# iteration) → DESCRIBE without auth (challenged) → DESCRIBE with auth
# (succeeds) — 3 requests. Some clients probe OPTIONS more than once first.
_MAX_AUTH_ATTEMPTS = 6


def _www_authenticate() -> bytes:
    # A fresh nonce per challenge is standard Digest hygiene even though
    # this proxy doesn't verify the response hash against it (see
    # _DIGEST_HEADER_RE's comment) — costs nothing and avoids looking
    # broken to any client that does check nonce freshness/replay.
    nonce = secrets.token_hex(16)
    return f'WWW-Authenticate: Digest realm="printops", nonce="{nonce}"\r\n'.encode()


class _AuthRequest:
    """One parsed RTSP request: the full raw request (request-line + every
    header, minus Authorization) plus the fields we needed to pull out of
    it along the way."""

    __slots__ = ("raw", "method", "authority", "path", "cseq", "token")

    def __init__(self, raw: bytes, method: bytes, authority: bytes, path: bytes) -> None:
        self.raw = raw
        self.method = method
        self.authority = authority
        self.path = path
        self.cseq: bytes = b"1"
        self.token: str | None = None


async def _read_request(reader: asyncio.StreamReader) -> _AuthRequest | None:
    """Read one full RTSP request (request-line + headers up to the blank
    line), preserving every header byte-for-byte except Authorization (not
    meaningful to go2rtc, which has no auth of its own) so nothing SETUP/
    PLAY/etc. actually need (Transport, Accept, User-Agent, ...) gets lost
    when this request is the one that turns out to carry valid credentials
    and gets forwarded on.

    Returns None on a malformed request-line, timeout, or EOF — callers
    treat that as "can't continue this connection".
    """
    try:
        first_line = await asyncio.wait_for(reader.readline(), timeout=_READ_TIMEOUT)
    except TimeoutError:
        return None
    if not first_line:
        return None

    match = _REQUEST_LINE_RE.match(first_line.rstrip(b"\r\n"))
    if not match:
        return None
    method, authority, path = match.groups()

    req = _AuthRequest(first_line, method, authority, path)
    header_lines: list[bytes] = []

    while True:
        try:
            line = await asyncio.wait_for(reader.readline(), timeout=_READ_TIMEOUT)
        except TimeoutError:
            return None
        if not line or line in (b"\r\n", b"\n"):
            break
        stripped = line.rstrip(b"\r\n")
        if m := _DIGEST_HEADER_RE.match(stripped):
            if um := _DIGEST_USERNAME_RE.search(m.group(1)):
                req.token = um.group(1).decode(errors="replace") or None
            continue  # drop the Authorization header from what we forward
        if m := _CSEQ_HEADER_RE.match(stripped):
            req.cseq = m.group(1)
        header_lines.append(line)

    req.raw = first_line + b"".join(header_lines) + b"\r\n"
    return req


async def _send_challenge(writer: asyncio.StreamWriter, cseq: bytes) -> None:
    try:
        writer.write(b"RTSP/1.0 401 Unauthorized\r\nCSeq: " + cseq + b"\r\n" + _www_authenticate() + b"\r\n")
        await writer.drain()
    except (ConnectionError, OSError):
        pass


async def _reject(writer: asyncio.StreamWriter, status: str, cseq: bytes = b"1") -> None:
    try:
        writer.write(f"RTSP/1.0 {status}\r\nCSeq: ".encode() + cseq + b"\r\n\r\n")
        await writer.drain()
    except (ConnectionError, OSError):
        pass
    finally:
        if not writer.is_closing():
            writer.close()


_OPTIONS_RESPONSE = b"Public: OPTIONS, SETUP, TEARDOWN, DESCRIBE, PLAY, PAUSE\r\n"


async def _authenticate(
    client_reader: asyncio.StreamReader, client_writer: asyncio.StreamWriter
) -> _AuthRequest | None:
    """Answer OPTIONS locally without requiring auth, then run the
    Digest challenge/response loop for the first request that actually
    touches the stream (DESCRIBE and onward).

    Real RTSP cameras/servers universally treat OPTIONS as unauthenticated
    capability negotiation — it reveals nothing but a method list — and
    ffmpeg's RTSP client (which is what go2rtc and HA's underlying stream
    backend use) matches that: it does not retry OPTIONS with credentials
    after a 401, only DESCRIBE. Challenging OPTIONS here would make every
    real client fail before it ever got a chance to prove it has a token.

    Returns the first successfully-authenticated non-OPTIONS request
    (still unforwarded), or None if the client never provided a valid
    token within _MAX_AUTH_ATTEMPTS.
    """
    req: _AuthRequest | None = None
    for _attempt in range(_MAX_AUTH_ATTEMPTS):
        req = await _read_request(client_reader)
        if req is None:
            return None

        if req.method.upper() == b"OPTIONS":
            try:
                client_writer.write(b"RTSP/1.0 200 OK\r\nCSeq: " + req.cseq + b"\r\n" + _OPTIONS_RESPONSE + b"\r\n")
                await client_writer.drain()
            except (ConnectionError, OSError):
                return None
            continue

        if req.token and await verify_camera_stream_token(req.token):
            return req

        if req.token:
            logger.info("RTSP passthrough: invalid or expired token")
            await _reject(client_writer, "401 Unauthorized", req.cseq)
            return None

        # No credentials offered yet — challenge and give the client a
        # chance to retry on the same connection with Digest credentials
        # (ffmpeg's RTSP client does this automatically for DESCRIBE).
        await _send_challenge(client_writer, req.cseq)

    logger.info("RTSP passthrough: no valid credentials after %d attempts", _MAX_AUTH_ATTEMPTS)
    if req is not None:
        await _reject(client_writer, "401 Unauthorized", req.cseq)
    return None


async def _handle(client_reader: asyncio.StreamReader, client_writer: asyncio.StreamWriter) -> None:
    printer_id: int | None = None
    upstream_writer: asyncio.StreamWriter | None = None
    try:
        req = await _authenticate(client_reader, client_writer)
        if req is None:
            return

        path_str = req.path.decode(errors="replace")
        stream_match = _STREAM_NAME_RE.match(path_str)
        if not stream_match:
            await _reject(client_writer, "404 Not Found", req.cseq)
            return
        printer_id = int(stream_match.group(2))

        async with async_session() as db:
            from backend.app.models.printer import Printer

            printer = (await db.execute(select(Printer).where(Printer.id == printer_id))).scalar_one_or_none()

        if printer is None:
            printer_id = None  # nothing to release
            await _reject(client_writer, "404 Not Found", req.cseq)
            return

        camera_source = get_camera_source(printer)
        if camera_source is None or not camera_source.has_h264:
            # Chamber-image / external-MJPEG-snapshot printers have no
            # RTSP producer in go2rtc for this to relay.
            printer_id = None
            await _reject(client_writer, "404 Not Found", req.cseq)
            return

        try:
            await go2rtc_registry.acquire(printer_id, camera_source)
        except RuntimeError:
            logger.error("RTSP passthrough: go2rtc unavailable for printer %s", printer_id)
            await _reject(client_writer, "503 Service Unavailable", req.cseq)
            printer_id = None  # already not acquired; nothing to release
            return

        try:
            upstream_reader, upstream_writer = await asyncio.wait_for(
                asyncio.open_connection("127.0.0.1", GO2RTC_INTERNAL_RTSP_PORT), timeout=5.0
            )
        except (TimeoutError, ConnectionError, OSError):
            logger.error("RTSP passthrough: could not reach go2rtc's internal RTSP port")
            await _reject(client_writer, "502 Bad Gateway", req.cseq)
            return

        proxy_url = f"rtsp://{req.authority.decode(errors='replace')}".encode()
        real_url = f"rtsp://127.0.0.1:{GO2RTC_INTERNAL_RTSP_PORT}".encode()

        logger.info("RTSP passthrough: session started for printer %s", printer_id)

        # Forward the now-authenticated request (all original headers
        # intact except Authorization, which go2rtc never asked for and
        # wouldn't understand — it has no auth of its own).
        upstream_writer.write(rewrite_rtsp_request_url(req.raw, proxy_url, real_url))
        await upstream_writer.drain()

        async def _fwd_to_upstream() -> None:
            try:
                while True:
                    data = await client_reader.read(65536)
                    if not data:
                        break
                    data = rewrite_rtsp_request_url(data, proxy_url, real_url)
                    upstream_writer.write(data)
                    await upstream_writer.drain()
            except (ConnectionError, OSError, asyncio.CancelledError, RuntimeError):
                pass
            finally:
                if not upstream_writer.is_closing():
                    try:
                        upstream_writer.close()
                    except OSError:
                        pass

        async def _fwd_to_client() -> None:
            try:
                while True:
                    data = await upstream_reader.read(65536)
                    if not data:
                        break
                    client_writer.write(data)
                    await client_writer.drain()
            except (ConnectionError, OSError, asyncio.CancelledError, RuntimeError):
                pass
            finally:
                if not client_writer.is_closing():
                    try:
                        client_writer.close()
                    except OSError:
                        pass

        await asyncio.gather(_fwd_to_upstream(), _fwd_to_client())
    except (ConnectionError, OSError, TimeoutError) as e:
        logger.debug("RTSP passthrough connection error: %s", e)
    finally:
        for w in (client_writer, upstream_writer):
            if w is not None and not w.is_closing():
                try:
                    w.close()
                except OSError:
                    pass
        if printer_id is not None:
            await go2rtc_registry.release(printer_id)
            logger.info("RTSP passthrough: session ended for printer %s", printer_id)


async def start(host: str, port: int) -> asyncio.Server:
    """Start the RTSP passthrough proxy. Caller keeps the returned server
    alive for the app's lifetime and closes it on shutdown."""
    server = await asyncio.start_server(_handle, host, port)
    logger.info("RTSP passthrough proxy listening on %s:%s", host, port)
    return server
