import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, Power, Trash2, Wind } from 'lucide-react';
import { api, type EquipmentInput } from '../../api/client';

const inputClass = 'h-10 w-full rounded-lg border border-bambu-dark-tertiary bg-bambu-dark px-3 text-white outline-none focus:border-bambu-green';
const initial = (): EquipmentInput => ({ equipment_type: 'dryer', name: '', is_active: true, acquisition_date: new Date().toISOString().slice(0, 10), acquisition_value: '0', service_years: '4', annual_hours: '500', maintenance_rate: '0.10', nominal_power_watts: '250' });

export function DeviceManagement({ locale }: { locale: string }) {
  const de = locale.startsWith('de');
  const queryClient = useQueryClient();
  const { data: dryers = [] } = useQuery({ queryKey: ['equipment'], queryFn: () => api.getEquipment() });
  const [draft, setDraft] = useState<EquipmentInput | null>(null);
  const create = useMutation({ mutationFn: api.createEquipment, onSuccess: () => { setDraft(null); void queryClient.invalidateQueries({ queryKey: ['equipment'] }); } });
  const update = useMutation({ mutationFn: ({ id, data }: { id: number; data: Partial<EquipmentInput> }) => api.updateEquipment(id, data), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['equipment'] }) });
  const remove = useMutation({ mutationFn: api.deleteEquipment, onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['equipment'] }) });
  const money = (value: string) => new Intl.NumberFormat(locale, { style: 'currency', currency: 'EUR' }).format(Number(value));
  return <section className="rounded-xl border border-bambu-dark-tertiary bg-bambu-dark-secondary p-5">
    <div className="flex items-center justify-between"><div className="flex items-center gap-3"><Wind className="h-5 w-5 text-bambu-orange" /><div><h3 className="font-semibold text-white">{de ? 'Trockner' : 'Dryers'}</h3><p className="text-xs text-bambu-gray">{de ? 'Zentrale Stammdaten für Trocknungs- und Kalkulationskosten.' : 'Central master data for drying and calculation costs.'}</p></div></div><button onClick={() => setDraft(initial())} className="inline-flex h-10 items-center gap-2 rounded-lg bg-bambu-orange px-4 font-medium text-black"><Plus className="h-4 w-4" />{de ? 'Trockner hinzufügen' : 'Add dryer'}</button></div>
    {draft && <div className="mt-4 grid gap-3 rounded-lg bg-bambu-dark p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs text-bambu-gray">{de ? 'Bezeichnung' : 'Name'}<input value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} className={inputClass} /></label><label className="text-xs text-bambu-gray">{de ? 'Anschaffungsdatum' : 'Acquisition date'}<input type="date" value={draft.acquisition_date} onChange={e => setDraft({ ...draft, acquisition_date: e.target.value })} className={inputClass} /></label>{[['acquisition_value', de ? 'Anschaffungswert' : 'Acquisition value'], ['service_years', de ? 'Nutzungsdauer Jahre' : 'Service life years'], ['annual_hours', de ? 'Betriebsstunden/Jahr' : 'Operating hours/year'], ['maintenance_rate', de ? 'Wartung (0–1)' : 'Maintenance (0–1)'], ['nominal_power_watts', de ? 'Leistung Watt' : 'Power watts']].map(([key, label]) => <label key={key} className="text-xs text-bambu-gray">{label}<input type="number" min="0" step="0.01" value={String(draft[key as keyof EquipmentInput])} onChange={e => setDraft({ ...draft, [key]: e.target.value })} className={inputClass} /></label>)}<div className="flex items-end gap-2"><button onClick={() => create.mutate(draft)} disabled={!draft.name || create.isPending} className="h-10 rounded-lg bg-bambu-green px-4 font-medium text-black disabled:opacity-50">{de ? 'Speichern' : 'Save'}</button><button onClick={() => setDraft(null)} className="h-10 rounded-lg bg-bambu-dark-secondary px-4 text-white">{de ? 'Abbrechen' : 'Cancel'}</button></div></div>}
    <div className="mt-4 grid gap-3 md:grid-cols-2">{dryers.map(dryer => <div key={dryer.id} className="rounded-lg border border-bambu-dark-tertiary bg-bambu-dark p-4"><div className="flex items-start justify-between"><div><strong className="text-white">{dryer.name}</strong><span className={`ml-2 rounded px-2 py-0.5 text-xs ${dryer.is_active ? 'bg-bambu-green/15 text-bambu-green' : 'bg-bambu-dark-tertiary text-bambu-gray'}`}>{dryer.is_active ? (de ? 'Aktiv' : 'Active') : (de ? 'Inaktiv' : 'Inactive')}</span></div><div className="flex gap-2"><button aria-label={de ? 'Aktivstatus ändern' : 'Toggle active'} onClick={() => update.mutate({ id: dryer.id, data: { is_active: !dryer.is_active } })} className="text-bambu-gray hover:text-white"><Power className="h-4 w-4" /></button><button aria-label={de ? 'Trockner löschen' : 'Delete dryer'} onClick={() => remove.mutate(dryer.id)} className="text-red-300"><Trash2 className="h-4 w-4" /></button></div></div><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-xs text-bambu-gray">{de ? 'Restwert' : 'Residual value'}</dt><dd className="text-white">{money(dryer.residual_value)}</dd></div><div><dt className="text-xs text-bambu-gray">{de ? 'Stundensatz' : 'Hourly rate'}</dt><dd className="text-white">{money(dryer.hourly_rate)}/h</dd></div><div><dt className="text-xs text-bambu-gray">{de ? 'Leistung' : 'Power'}</dt><dd className="text-white">{Number(dryer.nominal_power_watts)} W</dd></div><div><dt className="text-xs text-bambu-gray">{de ? 'Anschaffung' : 'Acquisition'}</dt><dd className="text-white">{money(dryer.acquisition_value)}</dd></div></dl></div>)}{dryers.length === 0 && <p className="text-sm text-bambu-gray">{de ? 'Noch keine Trockner angelegt.' : 'No dryers configured.'}</p>}</div>
  </section>;
}
