import { useEffect, useMemo, useState } from 'react';
import { Check, Copy, FileText, Save, X } from 'lucide-react';
import { api, ApiError, type BusinessProfileOption } from '../../api/client';
import { calculationsApi, type CalculationCreate, type CalculationDetail, type CalculationVariant } from '../../api/calculations';

interface Props { calculation: CalculationDetail | null; onClose: () => void; onSaved: () => void; locale: string }
const inputClass = 'mt-1 h-10 w-full rounded-lg border border-bambu-dark-tertiary bg-bambu-dark px-3 text-white outline-none focus:border-bambu-green';

const emptyVariant = (): CalculationVariant => ({
  name: 'Standard', is_preferred: true, sort_order: 0, price_method: 'target_margin', price_rate: '0.35',
  lines: [{ kind: 'printed_part', description: '', quantity: '1', unit_code: 'C62', unit_price: null, sort_order: 0 }],
  operations: [{ kind: 'printing', title: 'Platte 1', source_file: null, source_plate: 1, good_parts: 1, parts_per_run: 1, scrap_runs: 0, material_grams_per_run: '0', print_hours_per_run: '0', provenance: { source: 'manual' }, sort_order: 0, labor: [] }],
});

export function CalculationWorkspace({ calculation, onClose, onSaved, locale }: Props) {
  const de = locale.startsWith('de');
  const [profiles, setProfiles] = useState<BusinessProfileOption[]>([]);
  const [draft, setDraft] = useState<CalculationCreate>(() => calculation ? {
    business_profile_id: calculation.business_profile_id, customer_id: calculation.customer_id, title: calculation.title,
    currency: calculation.currency, notes: calculation.notes, variants: structuredClone(calculation.variants),
  } : { business_profile_id: 0, customer_id: null, title: '', currency: 'EUR', notes: null, variants: [emptyVariant()] });
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void api.getBusinessProfileOptions().then(items => { setProfiles(items.filter(item => item.is_active)); if (!calculation && draft.business_profile_id === 0 && items.length) setDraft(current => ({ ...current, business_profile_id: (items.find(item => item.is_default) ?? items[0]).id })); }); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const selected = draft.variants.find(variant => variant.is_preferred) ?? draft.variants[0];
  const totals = useMemo(() => {
    const sell = selected.lines.reduce((sum, line) => sum + Number(line.quantity) * Number(line.unit_price ?? 0), 0);
    const runs = selected.operations.reduce((sum, op) => sum + Math.ceil(op.good_parts / Math.max(1, op.parts_per_run)) + op.scrap_runs, 0);
    const grams = selected.operations.reduce((sum, op) => sum + (Math.ceil(op.good_parts / Math.max(1, op.parts_per_run)) + op.scrap_runs) * Number(op.material_grams_per_run), 0);
    const hours = selected.operations.reduce((sum, op) => sum + (Math.ceil(op.good_parts / Math.max(1, op.parts_per_run)) + op.scrap_runs) * Number(op.print_hours_per_run), 0);
    return { sell, runs, grams, hours };
  }, [selected]);
  const changeVariant = (index: number, update: (variant: CalculationVariant) => CalculationVariant) => setDraft(current => ({ ...current, variants: current.variants.map((variant, itemIndex) => itemIndex === index ? update(variant) : variant) }));
  const selectedIndex = Math.max(0, draft.variants.findIndex(variant => variant.is_preferred));
  const save = async () => { setSaving(true); setMessage(null); try { if (calculation) await calculationsApi.update(calculation.id, { ...draft, expected_version: calculation.version }); else await calculationsApi.create(draft); onSaved(); } catch (error) { setMessage(error instanceof ApiError && error.status === 409 ? (de ? 'Die Kalkulation wurde zwischenzeitlich geändert. Bitte neu laden.' : 'The calculation changed in the meantime. Reload it.') : error instanceof Error ? error.message : 'Error'); } finally { setSaving(false); } };
  const approve = async () => { if (!calculation) return; setSaving(true); try { await calculationsApi.approve(calculation.id, calculation.version); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } finally { setSaving(false); } };
  const template = async () => { if (!calculation) return; const name = window.prompt(de ? 'Name der Vorlage' : 'Template name', calculation.title); if (name) { await calculationsApi.createTemplate(calculation.id, name); setMessage(de ? 'Vorlage gespeichert.' : 'Template saved.'); } };
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/70 p-3 md:p-8"><div className="mx-auto max-w-7xl rounded-xl border border-bambu-dark-tertiary bg-bambu-dark-secondary shadow-2xl">
    <header className="sticky top-0 z-10 flex items-center justify-between border-b border-bambu-dark-tertiary bg-bambu-dark-secondary px-5 py-4"><div><h2 className="text-xl font-bold text-white">{calculation ? calculation.title : de ? 'Kalkulation hinzufügen' : 'Add calculation'}</h2><p className="text-sm text-bambu-gray">{calculation ? `K-${String(calculation.id).padStart(6, '0')} · v${calculation.version}` : de ? 'Konkrete Kundenanfrage' : 'Concrete customer request'}</p></div><button onClick={onClose} aria-label={de ? 'Schließen' : 'Close'} className="rounded p-2 text-bambu-gray hover:bg-bambu-dark"><X /></button></header>
    <main className="space-y-5 p-5">
      {message && <div className="rounded-lg border border-amber-500/50 bg-amber-500/10 p-3 text-sm text-amber-200">{message}</div>}
      <section><h3 className="mb-3 font-semibold text-white">1. {de ? 'Anfrage' : 'Request'}</h3><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">
        <label className="text-sm text-bambu-gray">{de ? 'Unternehmensprofil' : 'Business profile'}<select value={draft.business_profile_id} onChange={e => setDraft({ ...draft, business_profile_id: Number(e.target.value) })} className={inputClass}><option value={0}>{de ? 'Auswählen' : 'Select'}</option>{profiles.map(profile => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label>
        <label className="text-sm text-bambu-gray">{de ? 'Kunde (optional)' : 'Customer (optional)'}<input type="number" min="1" value={draft.customer_id ?? ''} onChange={e => setDraft({ ...draft, customer_id: e.target.value ? Number(e.target.value) : null })} className={inputClass} placeholder={de ? 'Kunden-ID' : 'Customer ID'} /></label>
        <label className="text-sm text-bambu-gray lg:col-span-2">{de ? 'Bezeichnung' : 'Title'}<input value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} className={inputClass} /></label>
      </div></section>
      <section><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold text-white">2. {de ? 'Varianten' : 'Variants'}</h3><button onClick={() => setDraft(current => ({ ...current, variants: [...current.variants.map(v => ({ ...v, is_preferred: false })), { ...structuredClone(selected), name: `${selected.name} ${current.variants.length + 1}`, is_preferred: true, sort_order: current.variants.length }] }))} className="inline-flex items-center gap-2 rounded bg-bambu-dark px-3 py-2 text-sm text-white"><Copy className="h-4 w-4" />{de ? 'Variante kopieren' : 'Clone variant'}</button></div><div className="flex flex-wrap gap-2">{draft.variants.map((variant, index) => <label key={`${variant.name}-${index}`} className={`flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 ${variant.is_preferred ? 'border-bambu-green text-white' : 'border-bambu-dark-tertiary text-bambu-gray'}`}><input type="radio" checked={variant.is_preferred} onChange={() => setDraft(current => ({ ...current, variants: current.variants.map((v, i) => ({ ...v, is_preferred: i === index })) }))} />{variant.name}</label>)}</div></section>
      <section><h3 className="mb-3 font-semibold text-white">3. {de ? 'Positionen' : 'Lines'}</h3><div className="space-y-2">{selected.lines.map((line, index) => <div key={index} className="grid gap-2 rounded-lg bg-bambu-dark p-3 md:grid-cols-[1fr_110px_130px]"><input value={line.description} onChange={e => changeVariant(selectedIndex, v => ({ ...v, lines: v.lines.map((item, i) => i === index ? { ...item, description: e.target.value } : item) }))} placeholder={de ? 'Bezeichnung' : 'Description'} className="h-10 rounded border border-bambu-dark-tertiary bg-bambu-dark-secondary px-3 text-white" /><input type="number" min="0.001" step="1" value={line.quantity} onChange={e => changeVariant(selectedIndex, v => ({ ...v, lines: v.lines.map((item, i) => i === index ? { ...item, quantity: e.target.value } : item) }))} className="h-10 rounded border border-bambu-dark-tertiary bg-bambu-dark-secondary px-3 text-white" /><input type="number" min="0" step="0.01" value={line.unit_price ?? ''} onChange={e => changeVariant(selectedIndex, v => ({ ...v, lines: v.lines.map((item, i) => i === index ? { ...item, unit_price: e.target.value || null } : item) }))} placeholder={de ? 'Preis netto' : 'Net price'} className="h-10 rounded border border-bambu-dark-tertiary bg-bambu-dark-secondary px-3 text-white" /></div>)}</div></section>
      <section><h3 className="mb-3 font-semibold text-white">4. {de ? 'Fertigung' : 'Production'}</h3>{selected.operations.map((op, index) => <div key={index} className="grid gap-3 rounded-lg bg-bambu-dark p-3 sm:grid-cols-2 lg:grid-cols-6"><label className="text-xs text-bambu-gray lg:col-span-2">{de ? 'Operation' : 'Operation'}<input value={op.title} onChange={e => changeVariant(selectedIndex, v => ({ ...v, operations: v.operations.map((item, i) => i === index ? { ...item, title: e.target.value } : item) }))} className={inputClass} /></label>{[['good_parts', de ? 'Gutteile' : 'Good parts'], ['parts_per_run', de ? 'Teile/Lauf' : 'Parts/run'], ['scrap_runs', de ? 'Ausschussläufe' : 'Scrap runs'], ['material_grams_per_run', 'g/Lauf'], ['print_hours_per_run', de ? 'h/Lauf' : 'h/run']].map(([key, label]) => <label key={key} className="text-xs text-bambu-gray">{label}<input type="number" min="0" step={key.includes('hours') ? '0.01' : '1'} value={String(op[key])} onChange={e => changeVariant(selectedIndex, v => ({ ...v, operations: v.operations.map((item, i) => i === index ? { ...item, [key]: key.includes('grams') || key.includes('hours') ? e.target.value : Number(e.target.value) } : item) }))} className={inputClass} /></label>)}</div>)}</section>
      <section><h3 className="mb-3 font-semibold text-white">5. {de ? 'Kosten & Preis' : 'Cost & price'}</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[de ? 'Druckläufe' : 'Print runs', totals.runs], ['Material', `${totals.grams.toFixed(2)} g`], [de ? 'Druckzeit' : 'Print time', `${totals.hours.toFixed(2)} h`], [de ? 'Verkaufspreis netto' : 'Net selling price', new Intl.NumberFormat(locale, { style: 'currency', currency: draft.currency }).format(totals.sell)]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-bambu-dark p-4"><span className="text-xs text-bambu-gray">{label}</span><strong className="mt-1 block text-lg text-white">{value}</strong></div>)}</div></section>
    </main>
    <footer className="sticky bottom-0 flex flex-wrap justify-end gap-3 border-t border-bambu-dark-tertiary bg-bambu-dark-secondary px-5 py-4"><button onClick={onClose} className="h-10 rounded-lg bg-bambu-dark px-4 text-white">{de ? 'Abbrechen' : 'Cancel'}</button>{calculation && <button onClick={() => void template()} className="inline-flex h-10 items-center gap-2 rounded-lg bg-bambu-dark px-4 text-white"><FileText className="h-4 w-4" />{de ? 'Als Vorlage speichern' : 'Save as template'}</button>}{calculation?.status === 'draft' && <button onClick={() => void approve()} disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-lg border border-bambu-green px-4 text-bambu-green"><Check className="h-4 w-4" />{de ? 'Freigeben' : 'Approve'}</button>}<button onClick={() => void save()} disabled={saving || !draft.title || !draft.business_profile_id} className="inline-flex h-10 items-center gap-2 rounded-lg bg-bambu-green px-4 font-medium text-black disabled:opacity-50"><Save className="h-4 w-4" />{de ? 'Speichern' : 'Save'}</button></footer>
  </div></div>;
}
