import { useEffect, useMemo, useState } from 'react';
import { Check, Copy, FileText, Plus, Save, Trash2, X } from 'lucide-react';
import { api, ApiError, type AppSettings, type BusinessProfileOption, type CustomerListItem } from '../../api/client';
import { calculationsApi, type CalculationCreate, type CalculationDetail, type CalculationPreview, type CalculationVariant } from '../../api/calculations';
import { LaborEditor } from './calculation/LaborEditor';

interface Props { calculation: CalculationDetail | null; onClose: () => void; onSaved: () => void; locale: string }
const inputClass = 'mt-1 h-10 w-full rounded-lg border border-bambu-dark-tertiary bg-bambu-dark px-3 text-white outline-none focus:border-bambu-green';

const emptyVariant = (): CalculationVariant => ({
  name: 'Standard', is_preferred: true, sort_order: 0, price_method: 'target_margin', price_rate: '0.35',
  lines: [{ kind: 'printed_part', description: '', quantity: '1', unit_code: 'C62', unit_price: null, sort_order: 0 }],
  operations: [{ kind: 'printing', title: 'Platte 1', source_file: null, source_plate: 1, good_parts: 1, parts_per_run: 1, scrap_runs: 0, material_grams_per_run: '0', print_hours_per_run: '0', provenance: { source: 'manual' }, sort_order: 0, labor: [] }],
});

export function CalculationWorkspace({ calculation, onClose, onSaved, locale }: Props) {
  const de = locale.startsWith('de');
  const [profiles, setProfiles] = useState<BusinessProfileOption[]>([]);
  const [customers, setCustomers] = useState<CustomerListItem[]>([]);
  const [settings, setSettings] = useState<AppSettings | null>(null);
  const [preview, setPreview] = useState<CalculationPreview | null>(null);
  const [draft, setDraft] = useState<CalculationCreate>(() => calculation ? {
    business_profile_id: calculation.business_profile_id, customer_id: calculation.customer_id, title: calculation.title,
    currency: calculation.currency, notes: calculation.notes, variants: structuredClone(calculation.variants),
  } : { business_profile_id: 0, customer_id: null, title: '', currency: 'EUR', notes: null, variants: [emptyVariant()] });
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void api.getBusinessProfileOptions().then(items => { setProfiles(items.filter(item => item.is_active)); if (!calculation && draft.business_profile_id === 0 && items.length) setDraft(current => ({ ...current, business_profile_id: (items.find(item => item.is_default) ?? items[0]).id })); }); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { void api.getSettings().then(setSettings); }, []);
  useEffect(() => {
    if (!draft.business_profile_id) { setCustomers([]); return; }
    void api.getCustomers({ businessProfileId: draft.business_profile_id, status: 'active', limit: 250, offset: 0 }).then(result => setCustomers(result.items));
  }, [draft.business_profile_id]);
  const selected = draft.variants.find(variant => variant.is_preferred) ?? draft.variants[0];
  const totals = useMemo(() => {
    const sell = selected.lines.reduce((sum, line) => sum + Number(line.quantity) * Number(line.unit_price ?? 0), 0);
    const runs = selected.operations.reduce((sum, op) => sum + Math.ceil(op.good_parts / Math.max(1, op.parts_per_run)) + op.scrap_runs, 0);
    const grams = selected.operations.reduce((sum, op) => sum + (Math.ceil(op.good_parts / Math.max(1, op.parts_per_run)) + op.scrap_runs) * Number(op.material_grams_per_run), 0);
    const hours = selected.operations.reduce((sum, op) => sum + (Math.ceil(op.good_parts / Math.max(1, op.parts_per_run)) + op.scrap_runs) * Number(op.print_hours_per_run), 0);
    return { sell, runs, grams, hours };
  }, [selected]);
  const changeVariant = (index: number, update: (variant: CalculationVariant) => CalculationVariant) => setDraft(current => ({ ...current, variants: current.variants.map((variant, itemIndex) => itemIndex === index ? update(variant) : variant) }));
  const selectedIndex = Math.max(0, draft.variants.findIndex(variant => variant.is_preferred));
  useEffect(() => {
    if (!settings || !selected) return;
    const operation = selected.operations.find(item => item.kind === 'printing') ?? selected.operations[0];
    if (!operation) { setPreview(null); return; }
    let defaults: Record<string, number | string> = {};
    try { defaults = JSON.parse(settings.calculation_defaults || '{}'); } catch { defaults = {}; }
    const n = (key: string, fallback = 0) => Number(defaults[key] ?? fallback);
    const timer = window.setTimeout(() => void calculationsApi.preview({
      good_parts: operation.good_parts, parts_per_run: operation.parts_per_run, scrap_runs: operation.scrap_runs,
      material_grams_per_run: operation.material_grams_per_run, material_price_per_kg: String(settings.default_filament_cost),
      print_hours_per_run: operation.print_hours_per_run, machine_cost_per_hour: '0',
      acquisition_value: String(n('acquisitionValue', 749)), residual_value: String(n('residualValue')),
      service_years: String(n('serviceYears', 4)), annual_hours: String(n('annualHours', 1200)), maintenance_rate: String(n('maintenancePercent', 25) / 100),
      printer_power_kw: String(n('printerPowerWatts', 200) / 1000), electricity_price_per_kwh: String(settings.energy_cost_per_kwh),
      drying_hours: String(n('dryingHours')), dryer_power_kw: String(n('dryerPowerWatts', 250) / 1000),
      labor: operation.labor, consumables: String(n('consumables', .75)), packaging: String(n('packaging', 2.5)),
      additional_costs: String(n('additionalCosts')), risk_rate: String(n('riskPercent', 8) / 100), shipping: String(n('shipping', 5.49)),
      price_method: selected.price_method, price_rate: selected.price_method === 'explicit_price' ? '0' : selected.price_rate,
      explicit_price: selected.price_method === 'explicit_price' ? selected.price_rate : String(n('explicitPrice')),
      discount_rate: String(n('discountPercent') / 100), tax_rate: String(n('taxPercent', 19) / 100),
      minimum_price: String(n('minimumPrice', 12)), minimum_profit: String(n('minimumProfit', 4)),
    }).then(setPreview).catch(() => setPreview(null)), 250);
    return () => window.clearTimeout(timer);
  }, [selected, settings]);
  const save = async () => { setSaving(true); setMessage(null); try { if (calculation) await calculationsApi.update(calculation.id, { ...draft, expected_version: calculation.version }); else await calculationsApi.create(draft); onSaved(); } catch (error) { setMessage(error instanceof ApiError && error.status === 409 ? (de ? 'Die Kalkulation wurde zwischenzeitlich geändert. Bitte neu laden.' : 'The calculation changed in the meantime. Reload it.') : error instanceof Error ? error.message : 'Error'); } finally { setSaving(false); } };
  const approve = async () => { if (!calculation) return; setSaving(true); try { await calculationsApi.approve(calculation.id, calculation.version); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } finally { setSaving(false); } };
  const template = async () => { if (!calculation) return; const name = window.prompt(de ? 'Name der Vorlage' : 'Template name', calculation.title); if (name) { await calculationsApi.createTemplate(calculation.id, name); setMessage(de ? 'Vorlage gespeichert.' : 'Template saved.'); } };
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/70 p-3 md:p-8"><div className="mx-auto max-w-7xl rounded-xl border border-bambu-dark-tertiary bg-bambu-dark-secondary shadow-2xl">
    <header className="sticky top-0 z-10 flex items-center justify-between border-b border-bambu-dark-tertiary bg-bambu-dark-secondary px-5 py-4"><div><h2 className="text-xl font-bold text-white">{calculation ? calculation.title : de ? 'Kalkulation hinzufügen' : 'Add calculation'}</h2><p className="text-sm text-bambu-gray">{calculation ? `K-${String(calculation.id).padStart(6, '0')} · v${calculation.version}` : de ? 'Konkrete Kundenanfrage' : 'Concrete customer request'}</p></div><button onClick={onClose} aria-label={de ? 'Schließen' : 'Close'} className="rounded p-2 text-bambu-gray hover:bg-bambu-dark"><X /></button></header>
    <main className="space-y-5 p-5">
      {message && <div className="rounded-lg border border-amber-500/50 bg-amber-500/10 p-3 text-sm text-amber-200">{message}</div>}
      <section><h3 className="mb-3 font-semibold text-white">1. {de ? 'Anfrage' : 'Request'}</h3><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">
        <label className="text-sm text-bambu-gray">{de ? 'Unternehmensprofil' : 'Business profile'}<select value={draft.business_profile_id} onChange={e => setDraft({ ...draft, business_profile_id: Number(e.target.value) })} className={inputClass}><option value={0}>{de ? 'Auswählen' : 'Select'}</option>{profiles.map(profile => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label>
        <label className="text-sm text-bambu-gray">{de ? 'Kunde (optional)' : 'Customer (optional)'}<select value={draft.customer_id ?? ''} onChange={e => setDraft({ ...draft, customer_id: e.target.value ? Number(e.target.value) : null })} className={inputClass}><option value="">{de ? 'Ohne Kundenzuordnung' : 'No customer'}</option>{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.account_number} · {customer.display_name}</option>)}</select></label>
        <label className="text-sm text-bambu-gray lg:col-span-2">{de ? 'Bezeichnung' : 'Title'}<input value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} className={inputClass} /></label>
      </div></section>
      <section><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold text-white">2. {de ? 'Varianten' : 'Variants'}</h3><button onClick={() => setDraft(current => ({ ...current, variants: [...current.variants.map(v => ({ ...v, is_preferred: false })), { ...structuredClone(selected), name: `${selected.name} ${current.variants.length + 1}`, is_preferred: true, sort_order: current.variants.length }] }))} className="inline-flex items-center gap-2 rounded bg-bambu-dark px-3 py-2 text-sm text-white"><Copy className="h-4 w-4" />{de ? 'Variante kopieren' : 'Clone variant'}</button></div><div className="flex flex-wrap gap-2">{draft.variants.map((variant, index) => <div key={index} className={`flex items-center gap-2 rounded-lg border px-3 py-2 ${variant.is_preferred ? 'border-bambu-green text-white' : 'border-bambu-dark-tertiary text-bambu-gray'}`}><input aria-label={de ? 'Bevorzugte Variante' : 'Preferred variant'} type="radio" checked={variant.is_preferred} onChange={() => setDraft(current => ({ ...current, variants: current.variants.map((v, i) => ({ ...v, is_preferred: i === index })) }))} /><input aria-label={de ? 'Variantenname' : 'Variant name'} value={variant.name} onChange={e => changeVariant(index, v => ({ ...v, name: e.target.value }))} className="w-40 bg-transparent outline-none" />{draft.variants.length > 1 && <button aria-label={de ? 'Variante löschen' : 'Delete variant'} onClick={() => setDraft(current => { const variants = current.variants.filter((_, i) => i !== index).map((v, i) => ({ ...v, sort_order: i })); if (!variants.some(v => v.is_preferred)) variants[0] = { ...variants[0], is_preferred: true }; return { ...current, variants }; })} className="text-red-300"><Trash2 className="h-4 w-4" /></button>}</div>)}</div></section>
      <section><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold text-white">3. {de ? 'Positionen' : 'Lines'}</h3><button onClick={() => changeVariant(selectedIndex, v => ({ ...v, lines: [...v.lines, { kind: 'printed_part', description: '', quantity: '1', unit_code: 'C62', unit_price: null, sort_order: v.lines.length }] }))} className="inline-flex items-center gap-2 rounded bg-bambu-dark px-3 py-2 text-sm text-white"><Plus className="h-4 w-4" />{de ? 'Position' : 'Line'}</button></div><div className="space-y-2">{selected.lines.map((line, index) => <div key={index} className="grid gap-2 rounded-lg bg-bambu-dark p-3 md:grid-cols-[1fr_110px_130px_40px]"><input value={line.description} onChange={e => changeVariant(selectedIndex, v => ({ ...v, lines: v.lines.map((item, i) => i === index ? { ...item, description: e.target.value } : item) }))} placeholder={de ? 'Bezeichnung' : 'Description'} className="h-10 rounded border border-bambu-dark-tertiary bg-bambu-dark-secondary px-3 text-white" /><input type="number" min="0.001" step="1" value={line.quantity} onChange={e => changeVariant(selectedIndex, v => ({ ...v, lines: v.lines.map((item, i) => i === index ? { ...item, quantity: e.target.value } : item) }))} className="h-10 rounded border border-bambu-dark-tertiary bg-bambu-dark-secondary px-3 text-white" /><input type="number" min="0" step="0.01" value={line.unit_price ?? ''} onChange={e => changeVariant(selectedIndex, v => ({ ...v, lines: v.lines.map((item, i) => i === index ? { ...item, unit_price: e.target.value || null } : item) }))} placeholder={de ? 'Preis netto' : 'Net price'} className="h-10 rounded border border-bambu-dark-tertiary bg-bambu-dark-secondary px-3 text-white" /><button aria-label={de ? 'Position löschen' : 'Delete line'} onClick={() => changeVariant(selectedIndex, v => ({ ...v, lines: v.lines.filter((_, i) => i !== index).map((item, i) => ({ ...item, sort_order: i })) }))} className="text-red-300"><Trash2 className="h-4 w-4" /></button></div>)}</div></section>
      <section><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold text-white">4. {de ? 'Fertigung' : 'Production'}</h3><button onClick={() => changeVariant(selectedIndex, v => ({ ...v, operations: [...v.operations, { ...emptyVariant().operations[0], title: `${de ? 'Platte' : 'Plate'} ${v.operations.length + 1}`, source_plate: v.operations.length + 1, sort_order: v.operations.length }] }))} className="inline-flex items-center gap-2 rounded bg-bambu-dark px-3 py-2 text-sm text-white"><Plus className="h-4 w-4" />{de ? 'Fertigungsschritt' : 'Operation'}</button></div>{selected.operations.map((op, index) => <div key={index} className="mb-2 grid gap-3 rounded-lg bg-bambu-dark p-3 sm:grid-cols-2 lg:grid-cols-7"><label className="text-xs text-bambu-gray lg:col-span-2">{de ? 'Operation' : 'Operation'}<input value={op.title} onChange={e => changeVariant(selectedIndex, v => ({ ...v, operations: v.operations.map((item, i) => i === index ? { ...item, title: e.target.value } : item) }))} className={inputClass} /></label>{[['good_parts', de ? 'Gutteile' : 'Good parts'], ['parts_per_run', de ? 'Teile/Lauf' : 'Parts/run'], ['scrap_runs', de ? 'Ausschussläufe' : 'Scrap runs'], ['material_grams_per_run', 'g/Lauf'], ['print_hours_per_run', de ? 'h/Lauf' : 'h/run']].map(([key, label]) => <label key={key} className="text-xs text-bambu-gray">{label}<input type="number" min="0" step={key.includes('hours') ? '0.01' : '1'} value={String(op[key])} onChange={e => changeVariant(selectedIndex, v => ({ ...v, operations: v.operations.map((item, i) => i === index ? { ...item, [key]: key.includes('grams') || key.includes('hours') ? e.target.value : Number(e.target.value) } : item) }))} className={inputClass} /></label>)}<button aria-label={de ? 'Fertigungsschritt löschen' : 'Delete operation'} onClick={() => changeVariant(selectedIndex, v => ({ ...v, operations: v.operations.filter((_, i) => i !== index).map((item, i) => ({ ...item, sort_order: i })) }))} className="self-end pb-3 text-red-300"><Trash2 className="h-4 w-4" /></button><LaborEditor operation={op} locale={locale} onChange={operation => changeVariant(selectedIndex, v => ({ ...v, operations: v.operations.map((item, i) => i === index ? operation : item) }))} /></div>)}</section>
      <section><h3 className="mb-3 font-semibold text-white">5. {de ? 'Kosten & Preis' : 'Cost & price'}</h3>
        <div className="mb-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm text-bambu-gray">{de ? 'Preisverfahren' : 'Pricing method'}<select value={selected.price_method} onChange={e => changeVariant(selectedIndex, v => ({ ...v, price_method: e.target.value as CalculationVariant['price_method'] }))} className={inputClass}><option value="target_margin">{de ? 'Zielmarge' : 'Target margin'}</option><option value="markup">{de ? 'Aufschlag' : 'Markup'}</option><option value="explicit_price">{de ? 'Fester Zielpreis' : 'Explicit price'}</option></select></label><label className="text-sm text-bambu-gray">{selected.price_method === 'target_margin' ? (de ? 'Zielmarge' : 'Target margin') : selected.price_method === 'markup' ? (de ? 'Aufschlag' : 'Markup') : (de ? 'Zielpreis' : 'Target price')}<input type="number" min="0" step="0.01" value={selected.price_rate} onChange={e => changeVariant(selectedIndex, v => ({ ...v, price_rate: e.target.value }))} className={inputClass} /></label></div>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[de ? 'Druckläufe' : 'Print runs', preview?.total_runs ?? totals.runs], ['Material', preview ? new Intl.NumberFormat(locale, { style: 'currency', currency: draft.currency }).format(Number(preview.material_cost)) : `${totals.grams.toFixed(2)} g`], [de ? 'Herstellkosten' : 'Production cost', preview ? new Intl.NumberFormat(locale, { style: 'currency', currency: draft.currency }).format(Number(preview.production_cost)) : '–'], [de ? 'Netto' : 'Net', preview ? new Intl.NumberFormat(locale, { style: 'currency', currency: draft.currency }).format(Number(preview.net_price)) : new Intl.NumberFormat(locale, { style: 'currency', currency: draft.currency }).format(totals.sell)], [de ? 'Deckungsbeitrag' : 'Contribution', preview ? new Intl.NumberFormat(locale, { style: 'currency', currency: draft.currency }).format(Number(preview.contribution)) : '–'], [de ? 'Effektive Marge' : 'Effective margin', preview ? `${(Number(preview.effective_margin) * 100).toFixed(1)} %` : '–'], [de ? 'Steuer' : 'Tax', preview ? new Intl.NumberFormat(locale, { style: 'currency', currency: draft.currency }).format(Number(preview.tax)) : '–'], [de ? 'Brutto' : 'Gross', preview ? new Intl.NumberFormat(locale, { style: 'currency', currency: draft.currency }).format(Number(preview.gross_price)) : '–']].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-bambu-dark p-4"><span className="text-xs text-bambu-gray">{label}</span><strong className="mt-1 block text-lg text-white">{value}</strong></div>)}</div></section>
    </main>
    <footer className="sticky bottom-0 flex flex-wrap justify-end gap-3 border-t border-bambu-dark-tertiary bg-bambu-dark-secondary px-5 py-4"><button onClick={onClose} className="h-10 rounded-lg bg-bambu-dark px-4 text-white">{de ? 'Abbrechen' : 'Cancel'}</button>{calculation && <button onClick={() => void template()} className="inline-flex h-10 items-center gap-2 rounded-lg bg-bambu-dark px-4 text-white"><FileText className="h-4 w-4" />{de ? 'Als Vorlage speichern' : 'Save as template'}</button>}{calculation?.status === 'draft' && <button onClick={() => void approve()} disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-lg border border-bambu-green px-4 text-bambu-green"><Check className="h-4 w-4" />{de ? 'Freigeben' : 'Approve'}</button>}<button onClick={() => void save()} disabled={saving || !draft.title || !draft.business_profile_id} className="inline-flex h-10 items-center gap-2 rounded-lg bg-bambu-green px-4 font-medium text-black disabled:opacity-50"><Save className="h-4 w-4" />{de ? 'Speichern' : 'Save'}</button></footer>
  </div></div>;
}
